# Generated by Django 3.0.4 on 2020-03-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalaccount',
            old_name='account_name',
            new_name='accountName',
        ),
        migrations.RenameField(
            model_name='internalaccount',
            old_name='external_account_association',
            new_name='externalAccountAssociation',
        ),
        migrations.RenameField(
            model_name='internalaccount',
            old_name='product_association',
            new_name='productAssociation',
        ),
        migrations.RenameField(
            model_name='internalaccount',
            old_name='source_id',
            new_name='sourceId',
        ),
    ]
