# Generated by Django 3.0.4 on 2020-03-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200329_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalaccount',
            old_name='externalAccountAssociation',
            new_name='externalAssociation',
        ),
        migrations.RemoveField(
            model_name='internalaccount',
            name='children',
        ),
    ]
