# Generated by Django 3.0.4 on 2020-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200329_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalaccount',
            name='accountName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internalaccount',
            name='externalAssociation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internalaccount',
            name='productAssociation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internalaccount',
            name='sourceId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internalaccount',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
