# Generated by Django 3.0.4 on 2020-03-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200329_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalaccount',
            old_name='externalAssociation',
            new_name='externalAccountAssociation',
        ),
    ]
