# Generated by Django 3.0.4 on 2020-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200413_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferID', models.BigIntegerField()),
                ('time', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=100)),
                ('requestUuid', models.UUIDField()),
            ],
        ),
    ]
