# Generated by Django 3.0.4 on 2020-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200329_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('exchangeAssociation', models.CharField(max_length=100)),
            ],
        ),
    ]
