# Generated by Django 3.0.4 on 2020-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_externalaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='internalaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='accountName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internalaccount',
            name='accountName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
