# Generated by Django 3.0.4 on 2020-04-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='msg',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
