# Generated by Django 3.0.4 on 2020-04-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200417_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.BigIntegerField(null=True),
        ),
    ]
